services:
  - type: web
    name: webshop
    env: docker
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_RETURN_URL
        sync: false
      - key: PAYPAL_CANCEL_URL
        sync: false